Implementation of nextPage getter for refactor + unit test
neurobagel/annotation_tool pull request #297
Opened 2023-01-05 21:15 UTC by jarmoza

This PR addresses #260. This getter makes use of the annotation tool's implicit page order. E.g. Given the current page of the app, what is the next (or following) page?

The `next-page` component has been altered to make use of the new getter name style `get*`.

The unit test sets each page as the current page and makes sure the proper 'next page' is being returned from the getter.

2023-01-05 22:09 UTC, rmanaem requested changes
Everything looks good! I added a small comment and requested a quick fix for this function:

https://github.com/neurobagel/annotation_tool/blob/16953c1be2b7c98c1cd7d562b597d65ac0dbdd0d/components/next-page.vue#L78-L82

I think the function should be renamed to `getNextPageButtonColor` and the return statement should be `return this.pageAccessible(this.getNextPage) ? "success" : "secondary"; `

2023-01-05 22:36 UTC, jarmoza commented on components/next-page.vue
>                  data-cy="button-nextpage"
In this case no, just because it's referring to the 'Next page' button rather than the getter.

2023-01-05 22:39 UTC, jarmoza commented
Thanks @rmanaem! For some reason can't reply to your first comment - but good catch re: the call to next page. In the case of the attribute and function, however, these are referring to the 'Next page' button itself so no need to rename it in line with the store getter.

2023-01-05 22:43 UTC, jarmoza commented
Should be good now, @rmanaem. Let me know what you think re: my replies.

2023-01-05 22:47 UTC, rmanaem commented
I see, I thought `nextPageButtonColor` function was referenced here before
https://github.com/neurobagel/annotation_tool/blob/9519f55719c03331549edac645cedd9a5966a646/components/next-page.vue#L19

2023-01-06 15:39 UTC, jarmoza commented
@rmanaem Good catch. That's a find and replace error – should still be `nextPageButtonColor`. I just fixed and committed.

2023-01-06 18:16 UTC, merged